language: go

go:
  - 1.13.x
  - 1.14.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - SHELLCHECK_VERSION=0.7.1 HADOLINT_VERSION=1.17.6

before_install:
  - wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64
  - tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest
  - chmod +x hadolint
  - ./shellcheck-stable/shellcheck --version
  - ./hadolint --version
  - make deps deps-test
  - go get -v github.com/mattn/goveralls
  - npm install -g codeclimate-test-reporter

script:
  - make all
  - go test -covermode=count ./parser ./recipe -coverprofile=coverage.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile coverage.out
  - codeclimate-test-reporter < coverage.out
  - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck bibop-docker'
  - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck bibop-entrypoint'
  - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck bibop-massive'
  - bash -c 'shopt -s globstar; ./shellcheck-stable/shellcheck bibop-multi-check'
  - ./hadolint centos6.docker
  - ./hadolint centos7.docker
