language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
  - tar xf shellcheck-latest.linux.x86_64.tar.xz
  - ./shellcheck-latest/shellcheck --version
  - make deps deps-test
  - npm install -g codeclimate-test-reporter

script:
  - make all
  - go test -covermode=count ./parser ./recipe -coverprofile=coverage.out
  - codeclimate-test-reporter < coverage.out
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck bibop-docker'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck bibop-entrypoint'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck bibop-massive'
