language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps deps-test
  - npm install -g codeclimate-test-reporter

script:
  - make all
  - go test -covermode=count ./parser ./recipe -coverprofile=coverage.out
  - codeclimate-test-reporter < coverage.out
