########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt all clean deps deps-test test

########################################################################################

all: bibop

bibop:
	go build bibop.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9

deps-test:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/check.v1

test:
	go test -covermode=count ./parser

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f bibop

########################################################################################
