name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 14 */15 * *'

permissions:
  actions: read
  contents: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SRC_DIR: src/github.com/${{ github.repository }}

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.18.x', '1.19.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Build binary
        working-directory: ${{env.SRC_DIR}}
        run: make all

      - name: Run tests
        working-directory: ${{env.SRC_DIR}}
        run: go test -covermode=count ./parser ./recipe -coverprofile=cover.out

      - name: Send coverage data
        uses: essentialkaos/goveralls-action@v1
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ${{env.SRC_DIR}}
          profile: cover.out
          parallel: true
          flag-name: linux-${{ matrix.go }}

  SendCoverage:
    name: Send Coverage
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Finish parallel tests
        uses: essentialkaos/goveralls-action@v1
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          parallel-finished: true

  Aligo:
    name: Aligo
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Check Golang sources with Aligo
        uses: essentialkaos/aligo-action@v1
        with:
          path: ${{env.SRC_DIR}}
          files: ./...

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: scripts/*

  Hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check dockerfiles with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          files: .docker/centos7.docker .docker/ol7.docker .docker/ol8.docker .docker/ol9.docker

  DockerBuild:
    name: Docker Build Check
    runs-on: ubuntu-latest

    needs: [Hadolint, Shellcheck, Aligo]

    env:
      REGISTRY: ghcr.io

    strategy:
      matrix:
        image: [ 'centos7', 'ol7', 'ol8', 'ol9' ]

    steps:
      - name: Check event type
        run: |
          if [[ "${{github.event_name}}" != "pull_request" ]] ; then
            echo "::notice::Event type is not 'pull_request', all job actions will be skipped"
          fi

          # This step is a hack for needs+if issue with actions
          # More info about issue: https://github.com/actions/runner/issues/491

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: ${{ github.event_name == 'pull_request' && env.DOCKERHUB_USERNAME != '' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker build --build-arg REGISTRY=${REGISTRY} -f .docker/${{matrix.image}}.docker -t ${{matrix.image}} .

      - name: Show info about built Docker image
        uses: essentialkaos/docker-info-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          image: ${{matrix.image}}
          show-labels: true
