name: Packer

on:
  push:
    tags:
      - v*

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
        id: go

      - name: Setup PATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "GOBIN=${{ github.workspace }}/bin" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Install GoPack
        run: |
          wget https://kaos.sh/gopack/SOURCES/gopack
          chmod +x gopack

      - name: Print GoPack version
        run: ./gopack --version

      - name: Pack sources
        run: ./gopack github.com/${{ github.repository }}

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 7
          path: '*.tar.bz2'
